name: Django Selenium Tests

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   test:
      runs-on: ubuntu-latest
      services:
         xvfb:
            image: selenium/standalone-firefox:latest
            ports:
               - 4444:4444
      steps:
         - uses: actions/checkout@v3
         - name: Set up Python
           uses: actions/setup-python@v4
           with:
              python-version: "3.11"
         - name: Install dependencies
           run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install webdriver-manager
         - name: Run migrations
           run: |
              python manage.py migrate
         - name: Run Selenium tests
           env:
              DISPLAY: :99
           run: |
              Xvfb :99 &
              python manage.py test tests.test_selenium -v 2
